### ISSUE TITLE
Container issue

### ISSUE THREAD

**Issue by dopecello** [brian-gee/samf-site#21]
Copy tailwind container props into SCSS container

**Comment by dopecello** [comment]
```scss
// | -------------------------------------------------------------
// | Container
// | -------------------------------------------------------------

@use 'breakpoint' as *;

.container {
  margin-left: auto; // ------->  previously margin: 0 auto
  margin-right: auto; // ---------^
  padding-left: calc(2rem / 2);
  padding-right: calc(2rem / 2); // -------- same problem with the padding. repeated across breakpoints
  max-width: 100%;

  @include breakpoint(medium) {
    padding-left: 2rem;
    padding-right: 2rem;
  }

  @include breakpoint(large) {
    padding-left: calc(2rem / 2);
    padding-right: calc(2rem / 2);
    max-width: 1200px;
  }

  &.stretch {
    max-width: 100%;
  }
}
```
